/-
  Putnam 2025 Problem B2 - Formalized Problem Statement

  Problem: Let f : [0,1] -> [0, infinity) be strictly increasing and continuous.
  Let R be the region bounded by x=0, x=1, y=0, and y=f(x).
  Let x_1 be the x-coordinate of the centroid of R.
  Let x_2 be the x-coordinate of the centroid of the solid generated by rotating R about the x-axis.
  Prove that x_1 < x_2.
-/

import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Set
import Mathlib.Order.Monotone.Basic
import Mathlib.Topology.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Tactic

namespace Putnam2025B2

open MeasureTheory Set Real intervalIntegral Filter Topology

/-- A valid function for the B2 problem:
    - Continuous on [0,1]
    - Strictly increasing on [0,1]
    - f(x) >= 0 on [0,1]
    Note: We do NOT require f(0) = 0; the problem only states f : [0,1] -> [0,infinity) -/
structure ValidFunction (f : ℝ → ℝ) : Prop where
  continuous : ContinuousOn f (Icc 0 1)
  strictly_increasing : StrictMonoOn f (Icc 0 1)
  range_nonneg : ∀ x ∈ Icc 0 1, f x ≥ 0

/-- The x-coordinate of the centroid of region R under f -/
noncomputable def centroid_region (f : ℝ → ℝ) : ℝ :=
  (∫ x in (0:ℝ)..1, x * f x) / (∫ x in (0:ℝ)..1, f x)

/-- The x-coordinate of the centroid of the solid of revolution -/
noncomputable def centroid_solid (f : ℝ → ℝ) : ℝ :=
  (∫ x in (0:ℝ)..1, x * (f x)^2) / (∫ x in (0:ℝ)..1, (f x)^2)

/-- Putnam 2025 B2: For any strictly increasing continuous f : [0,1] -> [0,infinity),
    the centroid of the region under f has smaller x-coordinate than the centroid
    of the solid of revolution. -/
theorem putnam_2025_B2 (f : ℝ → ℝ) (hf : ValidFunction f) :
    centroid_region f < centroid_solid f := by
  sorry

end Putnam2025B2
